import type { Violation, ApprovalRequest, Trip, PolicyRule, SpendSummary, InboxItem } from './types'

export const MOCK_VIOLATIONS: Violation[] = [
  {
    id: 'v1',
    type: 'split_charge',
    severity: 'high',
    merchantName: 'WSDOT COMMERCIAL VEHIC',
    amount: 6234.87,
    date: '2026-03-03',
    cardNumber: '3001',
    reason: 'Three charges from the same commercial vehicle permit authority totalling $6,234.87 on a single day — consistent with splitting to avoid the $500 pre-authorization threshold.',
    policyRule: 'All expenses over $50 must be pre-authorized by your manager.',
    transaction: { id: 't1', merchantName: 'WSDOT COMMERCIAL VEHIC', amount: 2344.29, city: 'Tumwater', state: 'WA', country: 'USA', mcc: '9399', transactionDate: '2026-03-03', postingDate: '2026-03-04', debitCredit: 'Debit', description: 'WSDOT COMMERCIAL VEHIC TUMWATER WA', category: '0001', transactionCode: '3001', postalCode: '98504', conversionRate: 1.3853 },
    relatedTransactions: [
      { id: 't1b', merchantName: 'WSDOT COMMERCIAL VEHIC', amount: 1842.15, city: 'Tumwater', state: 'WA', country: 'USA', mcc: '9399', transactionDate: '2026-03-03', postingDate: '2026-03-04', debitCredit: 'Debit', description: 'WSDOT COMMERCIAL VEHIC TUMWATER WA', category: '0001', transactionCode: '3001', postalCode: '98504', conversionRate: 1.3853 },
      { id: 't1c', merchantName: 'WSDOT COMMERCIAL VEHIC', amount: 2048.43, city: 'Tumwater', state: 'WA', country: 'USA', mcc: '9399', transactionDate: '2026-03-03', postingDate: '2026-03-04', debitCredit: 'Debit', description: 'WSDOT COMMERCIAL VEHIC TUMWATER WA', category: '0001', transactionCode: '3001', postalCode: '98504', conversionRate: 1.3853 },
    ],
    transactionId: 't1',
  },
  {
    id: 'v2',
    type: 'split_charge',
    severity: 'high',
    merchantName: 'KWIK TRIP #234',
    amount: 2054.63,
    date: '2026-02-24',
    cardNumber: '3001',
    reason: 'Four charges at the same fuel station on one day total $2,054.63. Pattern suggests multiple transactions to stay under approval threshold.',
    policyRule: 'All expenses over $50 must be pre-authorized by your manager.',
    transaction: { id: 't2', merchantName: 'KWIK TRIP #234', amount: 612.44, city: 'Unknown', state: 'WI', country: 'USA', mcc: '5541', transactionDate: '2026-02-24', postingDate: '2026-02-25', debitCredit: 'Debit', description: 'KWIK TRIP #234', category: '0001', transactionCode: '3001', postalCode: '', conversionRate: 1.389 },
    transactionId: 't2',
  },
  {
    id: 'v3',
    type: 'personal_expense',
    severity: 'high',
    merchantName: 'SOFTMOC 8464 WHITBY ON',
    amount: 176.39,
    date: '2025-09-09',
    cardNumber: '3001',
    reason: 'Retail shoe purchase (MCC 5661) on a corporate fleet card. No business justification exists for a shoe store charge in a trucking operation.',
    policyRule: 'Use of corporate credit cards to charge personal expenses is prohibited.',
    transaction: { id: 't3', merchantName: 'SOFTMOC 8464', amount: 176.39, city: 'Whitby', state: 'ON', country: 'CAN', mcc: '5661', transactionDate: '2025-09-08', postingDate: '2025-09-09', debitCredit: 'Debit', description: 'SOFTMOC 8464 WHITBY ON', category: '0001', transactionCode: '3001', postalCode: 'L1N2C3', conversionRate: 0 },
    transactionId: 't3',
  },
  {
    id: 'v4',
    type: 'personal_expense',
    severity: 'medium',
    merchantName: 'SKIPDISHES WINNIPEG',
    amount: 27.13,
    date: '2025-09-11',
    cardNumber: '3001',
    reason: 'Food delivery app charge on a corporate fleet card. Personal food delivery is not a reimbursable business expense unless dining with a customer.',
    policyRule: 'Use of corporate credit cards to charge personal expenses is prohibited.',
    transaction: { id: 't4', merchantName: 'SKIPDISHES', amount: 27.13, city: 'Winnipeg', state: 'MB', country: 'CAN', mcc: '5812', transactionDate: '2025-09-10', postingDate: '2025-09-11', debitCredit: 'Debit', description: 'SKIPDISHES WINNIPEG MB', category: '0001', transactionCode: '3001', postalCode: 'R3C 0T8', conversionRate: 0 },
    transactionId: 't4',
  },
  {
    id: 'v5',
    type: 'personal_expense',
    severity: 'medium',
    merchantName: 'TLF*THE AWESOME BLOSSO',
    amount: 150.09,
    date: '2025-09-11',
    cardNumber: '3001',
    reason: 'Two florist charges totalling $150.09 on a fleet card. Floral purchases have no business justification in fleet operations.',
    policyRule: 'Use of corporate credit cards to charge personal expenses is prohibited.',
    transaction: { id: 't5', merchantName: 'TLF*THE AWESOME BLOSSO', amount: 11.55, city: 'Edmonton', state: 'AB', country: 'CAN', mcc: '5992', transactionDate: '2025-09-08', postingDate: '2025-09-09', debitCredit: 'Debit', description: 'TLF*THE AWESOME BLOSSO EDMONTON AB', category: '0001', transactionCode: '3001', postalCode: 'T5M 4G5', conversionRate: 0 },
    transactionId: 't5',
  },
  {
    id: 'v6',
    type: 'unauthorized_category',
    severity: 'medium',
    merchantName: 'L OCA GIFTCARD',
    amount: 75.00,
    date: '2025-09-04',
    cardNumber: '3001',
    reason: 'Gift card purchase (MCC 5947) on a corporate fleet card. Gift card purchases are not an approved expense category and can be used to obscure the actual expense.',
    policyRule: 'Abuse of this business expense policy, including falsifying expense reports, is expressly prohibited.',
    transaction: { id: 't6', merchantName: 'L OCA GIFTCARD', amount: 75.00, city: 'Vancouver', state: 'BC', country: 'CAN', mcc: '5947', transactionDate: '2025-09-02', postingDate: '2025-09-04', debitCredit: 'Debit', description: 'L OCA GIFTCARD VANCOUVER BC', category: '0001', transactionCode: '3001', postalCode: 'V6B2M1', conversionRate: 0 },
    transactionId: 't6',
  },
]

export const MOCK_APPROVALS: ApprovalRequest[] = [
  {
    id: 'a1',
    status: 'pending',
    requestedAt: '2025-09-04',
    aiRecommendation: 'approve',
    aiReasoning: 'Bulk tire purchase from Michelin Canada — $51,182.84 is consistent with fleet-scale tire procurement. Card 3001 has made similar large maintenance purchases this quarter. The amount exceeds the $50 pre-authorization threshold but aligns with normal fleet maintenance cycles. Department has sufficient budget remaining. Recommend: Approve with receipt verification.',
    departmentBudget: { used: 187000, total: 320000, remaining: 133000, period: 'Q4 2025' },
    transaction: { id: 'ta1', merchantName: 'MNA*MICHELIN CANADA', amount: 51182.84, city: 'Montreal', state: 'QC', country: 'CAN', mcc: '5532', transactionDate: '2025-09-03', postingDate: '2025-09-04', debitCredit: 'Debit', description: 'MNA*MICHELIN CANADA 877-724-2835 QC', category: '0001', transactionCode: '3001', postalCode: 'H7T 2P6', conversionRate: 0 },
    employeeHistory: [
      { id: 'th1', merchantName: 'SKEANS PNEUMATIC AND A', amount: 311.05, city: 'Calgary', state: 'AB', country: 'CAN', mcc: '5085', transactionDate: '2025-09-04', postingDate: '2025-09-05', debitCredit: 'Debit', description: '', category: '0001', transactionCode: '3001', postalCode: 'T2C4R1', conversionRate: 0 },
      { id: 'th2', merchantName: 'KINGPIN TRAILERS LTD', amount: 103.20, city: 'Edmonton', state: 'AB', country: 'CAN', mcc: '5561', transactionDate: '2025-09-02', postingDate: '2025-09-03', debitCredit: 'Debit', description: '', category: '0001', transactionCode: '3001', postalCode: 'T5V 1A1', conversionRate: 0 },
      { id: 'th3', merchantName: "LOVE'S #0340 INSIDE", amount: 454.68, city: 'Las Vegas', state: 'NV', country: 'USA', mcc: '5541', transactionDate: '2025-09-02', postingDate: '2025-09-03', debitCredit: 'Debit', description: '', category: '0001', transactionCode: '3001', postalCode: '89165', conversionRate: 1.3818 },
      { id: 'th4', merchantName: 'COFFEE CUP #8', amount: 774.35, city: 'Vivian', state: 'SD', country: 'USA', mcc: '5541', transactionDate: '2025-09-02', postingDate: '2025-09-03', debitCredit: 'Debit', description: '', category: '0001', transactionCode: '3001', postalCode: '57576', conversionRate: 1.3818 },
      { id: 'th5', merchantName: "LOVE'S TIRE CARE #0374", amount: 94.31, city: 'Barstow', state: 'CA', country: 'USA', mcc: '7538', transactionDate: '2025-09-02', postingDate: '2025-09-03', debitCredit: 'Debit', description: '', category: '0001', transactionCode: '3001', postalCode: '92311', conversionRate: 1.3817 },
    ],
  },
  {
    id: 'a2',
    status: 'pending',
    requestedAt: '2025-09-11',
    aiRecommendation: 'review',
    aiReasoning: 'Amazon purchase of $318.42 on a fleet card. While some Amazon purchases may be legitimate supply orders, this amount on card 3001 — which has 3 personal expense violations this period — warrants review. Request itemized receipt before approving.',
    departmentBudget: { used: 187000, total: 320000, remaining: 133000, period: 'Q4 2025' },
    transaction: { id: 'ta2', merchantName: 'AMZN Mktp CA*IH9VH1PN3', amount: 318.42, city: 'Online', state: 'ON', country: 'CAN', mcc: '4816', transactionDate: '2025-09-10', postingDate: '2025-09-11', debitCredit: 'Debit', description: 'AMZN Mktp CA*IH9VH1PN3 866-216-1072 ON', category: '0001', transactionCode: '3001', postalCode: 'M5J 2T3', conversionRate: 0 },
    employeeHistory: [],
  },
]

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip1',
    name: 'Edmonton → Pacific Northwest loop',
    startLocation: 'Edmonton, AB',
    endLocation: 'Edmonton, AB',
    startDate: '2025-09-07',
    endDate: '2025-09-15',
    totalSpend: 12847.22,
    transactionCount: 18,
    cardNumber: '3001',
    policyStatus: 'compliant',
    aiSummary: '9-day run through BC, WA, and OR with return via ID and MT. Charges include fuel at Flying J and Pilot stops, WSDOT commercial vehicle permits, one car wash in Lodi CA, and a hotel stay in Moosomin SK. All charges consistent with the route and fleet operations. No policy violations detected.',
    categoryBreakdown: [
      { category: 'Fuel', amount: 7452.10, percentage: 58 },
      { category: 'Permits', amount: 3882.50, percentage: 30 },
      { category: 'Lodging', amount: 987.63, percentage: 8 },
      { category: 'Other', amount: 524.99, percentage: 4 },
    ],
    transactions: [],
  },
  {
    id: 'trip2',
    name: 'Western Canada + US midwest run',
    startLocation: 'Edmonton, AB',
    endLocation: 'Edmonton, AB',
    startDate: '2025-09-02',
    endDate: '2025-09-06',
    totalSpend: 56842.15,
    transactionCount: 22,
    cardNumber: '3001',
    policyStatus: 'violations',
    aiSummary: '5-day run covering AB, SK, ND, SD, MN, IA and return. Large Michelin tire purchase ($51,182.84) accounts for 90% of spend and requires approval. Remaining charges are routine fuel and permit costs. One personal expense flagged: gift card purchase in Vancouver.',
    categoryBreakdown: [
      { category: 'Tires / Parts', amount: 51182.84, percentage: 90 },
      { category: 'Fuel', amount: 3842.15, percentage: 7 },
      { category: 'Permits', amount: 1242.00, percentage: 2 },
      { category: 'Other', amount: 575.16, percentage: 1 },
    ],
    transactions: [],
  },
  {
    id: 'trip3',
    name: 'Texas + Oklahoma corridor',
    startLocation: 'Edmonton, AB',
    endLocation: 'Edmonton, AB',
    startDate: '2025-09-08',
    endDate: '2025-09-15',
    totalSpend: 8234.77,
    transactionCount: 14,
    cardNumber: '3001',
    policyStatus: 'pending_review',
    aiSummary: "Southern US run through TX and OK. TXDMV oversize permits, fuel at TOOT'N TOTUM and Road Ranger, OKC size and weight permits. One anomaly: $496 charge at TOOT'N TOTUM followed by another $511 charge the same day — possible split. Recommend review.",
    categoryBreakdown: [
      { category: 'Fuel', amount: 4821.33, percentage: 59 },
      { category: 'Permits', amount: 2834.44, percentage: 34 },
      { category: 'Other', amount: 579.00, percentage: 7 },
    ],
    transactions: [],
  },
]

export const MOCK_POLICY_RULES: PolicyRule[] = [
  {
    id: 'p1',
    title: 'Pre-authorization threshold',
    description: 'All expenses over $50.00 must be pre-authorized by your manager and receipts are required before any expense is reimbursed.',
    category: 'Approval',
    threshold: 50,
    thresholdUnit: 'CAD',
    isActive: true,
    extractedFrom: 'Business Expenses — General Policy',
    severity: 'high',
  },
  {
    id: 'p2',
    title: 'No personal charges on corporate cards',
    description: 'Use of corporate credit cards to charge personal expenses is prohibited. Brim may choose to restrict usage or revoke corporate cards where consistent abuse is evident.',
    category: 'Corporate Cards',
    isActive: true,
    extractedFrom: 'Corporate Credit Cards',
    severity: 'high',
  },
  {
    id: 'p3',
    title: 'Alcohol restriction',
    description: 'Unless dining with a customer, expensing alcoholic beverages is not permitted. Names of guests and purpose must be listed with receipts for supplier entertainment.',
    category: 'Entertainment',
    isActive: true,
    extractedFrom: 'Business Travel — Supplier Entertainment',
    severity: 'medium',
  },
  {
    id: 'p4',
    title: 'Meal tip limit',
    description: 'Tips may be expensed up to 15% for services and porterage. Meal tips are included with meal claims and will not be reimbursed above 20%.',
    category: 'Meals',
    threshold: 20,
    thresholdUnit: '%',
    isActive: true,
    extractedFrom: 'Business Travel — Tips & Gratuities',
    severity: 'low',
  },
  {
    id: 'p5',
    title: 'Receipt submission deadline',
    description: 'You should use best efforts to submit receipts within the current month. Abuse of this policy including falsifying expense reports is expressly prohibited.',
    category: 'Receipts',
    isActive: true,
    extractedFrom: 'Business Expenses — General Policy',
    severity: 'medium',
  },
  {
    id: 'p6',
    title: 'Car rental sharing',
    description: 'If there are multiple company team members at the same location, you may be required to share a car. Car rental, parking and gasoline receipts are required for reimbursement.',
    category: 'Transportation',
    isActive: true,
    extractedFrom: 'Business Travel — Car Rental',
    severity: 'low',
  },
]

export const MOCK_SPEND_SUMMARY: SpendSummary = {
  totalSpend: 2717509.64,
  transactionCount: 4235,
  avgTransaction: 641.68,
  openViolations: 6,
  pendingApprovals: 2,
  categoryBreakdown: [
    { category: 'Fuel', amount: 674495.27, color: '#378ADD' },
    { category: 'Permits', amount: 356661.00, color: '#BA7517' },
    { category: 'Tires / Parts', amount: 210994.64, color: '#7F77DD' },
    { category: 'Repairs', amount: 29174.35, color: '#888780' },
    { category: 'Car Wash', amount: 18599.51, color: '#5DCAA5' },
    { category: 'Tolls', amount: 16645.80, color: '#AFA9EC' },
    { category: 'Online / Amazon', amount: 8918.28, color: '#85B7EB' },
    { category: 'Other', amount: 401521.79, color: '#555' },
  ],
  monthlyTrend: [
    { month: 'Sep 2025', amount: 412840 },
    { month: 'Oct 2025', amount: 489320 },
    { month: 'Nov 2025', amount: 398150 },
    { month: 'Dec 2025', amount: 521480 },
    { month: 'Jan 2026', amount: 443920 },
    { month: 'Feb 2026', amount: 451800 },
  ],
  topMerchants: [
    { name: 'DTOPS SINGLE CROSSING', amount: 4648.47, count: 167 },
    { name: 'AB TRANSP 403-340-5075', amount: 18420.50, count: 158 },
    { name: 'NDHP-E PERMIT', amount: 5314.76, count: 134 },
    { name: 'SD DEPT OF TRANS OPS', amount: 7842.33, count: 131 },
    { name: 'TXDMV OS PERMIT TPE', amount: 32841.15, count: 102 },
    { name: 'MNA*MICHELIN CANADA', amount: 210994.64, count: 4 },
    { name: "LOVE'S (all locations)", amount: 48420.88, count: 89 },
    { name: 'FLYING J (all locations)', amount: 52184.33, count: 76 },
  ],
}

export const MOCK_INBOX_ITEMS: InboxItem[] = [
  {
    id: 'i1', type: 'violation', severity: 'high', isRead: false, isResolved: false,
    title: 'WSDOT COMMERCIAL VEHIC', subtitle: '3 charges · same day · Card 3001',
    amount: 6234.87, date: '2026-03-03',
    aiBrief: 'Three charges from the same commercial vehicle permit authority totalling $6,234.87 on a single day — consistent with splitting to avoid the $500 pre-authorization threshold.',
    cardNumber: '3001', violation: MOCK_VIOLATIONS[0],
  },
  {
    id: 'i2', type: 'violation', severity: 'high', isRead: false, isResolved: false,
    title: 'KWIK TRIP #234', subtitle: '4 charges · same day · Card 3001',
    amount: 2054.63, date: '2026-02-24',
    aiBrief: 'Four charges at the same fuel station on one day total $2,054.63. Each charge is under $500 individually — pattern strongly suggests intentional splitting to avoid the pre-authorization threshold.',
    cardNumber: '3001', violation: MOCK_VIOLATIONS[1],
  },
  {
    id: 'i3', type: 'approval', isRead: false, isResolved: false,
    title: 'MNA*MICHELIN CANADA', subtitle: 'Approval needed · over threshold · Card 3001',
    amount: 51182.84, date: '2025-09-04',
    aiBrief: 'Bulk tire purchase from Michelin Canada. Consistent with fleet maintenance patterns — similar purchases made this quarter. Budget has sufficient room. Recommendation: Approve with receipt verification.',
    cardNumber: '3001', approval: MOCK_APPROVALS[0],
  },
  {
    id: 'i4', type: 'violation', severity: 'high', isRead: false, isResolved: false,
    title: 'SOFTMOC 8464 WHITBY ON', subtitle: 'Shoe store · Card 3001',
    amount: 176.39, date: '2025-09-09',
    aiBrief: 'Retail shoe purchase on a corporate fleet card. MCC 5661 (shoe stores) has no valid business use in a trucking operation. Corporate card policy prohibits personal expenses.',
    cardNumber: '3001', violation: MOCK_VIOLATIONS[2],
  },
  {
    id: 'i5', type: 'violation', severity: 'medium', isRead: false, isResolved: false,
    title: 'SKIPDISHES WINNIPEG', subtitle: 'Food delivery · Card 3001',
    amount: 27.13, date: '2025-09-11',
    aiBrief: 'Food delivery app charge on a corporate fleet card. Personal food delivery is not a reimbursable business expense unless dining with a customer, in which case guest names and purpose must be documented.',
    cardNumber: '3001', violation: MOCK_VIOLATIONS[3],
  },
  {
    id: 'i6', type: 'approval', isRead: true, isResolved: false,
    title: 'AMZN Mktp CA*IH9VH1PN3', subtitle: 'Review needed · Card 3001',
    amount: 318.42, date: '2025-09-11',
    aiBrief: 'Amazon purchase on a fleet card that has 3 personal expense violations this period. Amount is above threshold. Request itemized receipt before approving.',
    cardNumber: '3001', approval: MOCK_APPROVALS[1],
  },
  {
    id: 'i7', type: 'violation', severity: 'medium', isRead: true, isResolved: false,
    title: 'L OCA GIFTCARD + AWESOME BLOSSO', subtitle: 'Gift card + florist · Card 3001',
    amount: 225.09, date: '2025-09-09',
    aiBrief: 'Gift card ($75) and florist charges ($150.09 across two transactions) on a fleet card. Neither category has a business justification in fleet operations. Gift cards can obscure the true nature of an expense.',
    cardNumber: '3001', violation: MOCK_VIOLATIONS[5],
  },
]
